# 基础镜像
FROM nginx
# author
MAINTAINER verify

# 挂载目录
VOLUME /home/verify/projects/verify-ui
# 创建目录
RUN mkdir -p /home/verify/projects/verify-ui
# 指定路径
WORKDIR /home/verify/projects/verify-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/verify/projects/verify-ui
