# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER verify

# 挂载目录
VOLUME /home/verify
# 创建目录
RUN mkdir -p /home/verify
# 指定路径
WORKDIR /home/verify
# 复制jar文件到路径
COPY ./jar/verify-auth.jar /home/verify/verify-auth.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","verify-auth.jar"]
